name: 🧪 QA - Testes Automatizados ERP

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Rodar testes diariamente às 9h UTC (6h Brasília)
    - cron: '0 9 * * *'
  workflow_dispatch: # Permitir execução manual

jobs:
  testes-producao:
    name: ✅ Validar Casos de Produção
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: 📥 Checkout código
      uses: actions/checkout@v3
    
    - name: 🟢 Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: 📦 Instalar dependências
      run: npm ci
    
    - name: 🌐 Setup Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: 🧪 Executar Testes de Produção
      run: npm run test:producao
      continue-on-error: true
    
    - name: 📊 Upload Relatório de Produção
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: relatorio-producao-node-${{ matrix.node-version }}
        path: reports/relatorio-producao.json
        retention-days: 30
    
    - name: 📸 Upload Screenshots (se houver falhas)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: screenshots-falhas-producao
        path: screenshots/
        retention-days: 7

  testes-novos:
    name: 🆕 Executar Novos Casos de Teste
    runs-on: ubuntu-latest
    needs: testes-producao # Rodar após testes de produção
    
    steps:
    - name: 📥 Checkout código
      uses: actions/checkout@v3
    
    - name: 🟢 Setup Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: 📦 Instalar dependências
      run: npm ci
    
    - name: 🌐 Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: 🧪 Executar Novos Casos de Teste
      run: npm run test:novos
      continue-on-error: true
    
    - name: 📊 Upload Relatório Novos Casos
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: relatorio-novos-casos
        path: reports/relatorio-novos.json
        retention-days: 30

  analise-qualidade:
    name: 📈 Análise de Qualidade
    runs-on: ubuntu-latest
    needs: [testes-producao, testes-novos]
    if: always()
    
    steps:
    - name: 📥 Checkout código
      uses: actions/checkout@v3
    
    - name: 📊 Download Relatórios
      uses: actions/download-artifact@v3
      with:
        path: reports-consolidados/
    
    - name: 📈 Gerar Resumo
      run: |
        echo "## 📊 Resumo da Execução" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ✅ Testes de Produção" >> $GITHUB_STEP_SUMMARY
        echo "- Node 18.x: Executado" >> $GITHUB_STEP_SUMMARY
        echo "- Node 20.x: Executado" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🆕 Novos Casos de Teste" >> $GITHUB_STEP_SUMMARY
        echo "- Status: Executado" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "📄 Relatórios disponíveis nos artifacts da execução" >> $GITHUB_STEP_SUMMARY

  notificacao:
    name: 📧 Notificar Resultados
    runs-on: ubuntu-latest
    needs: [testes-producao, testes-novos]
    if: always()
    
    steps:
    - name: ✅ Testes Passaram
      if: needs.testes-producao.result == 'success' && needs.testes-novos.result == 'success'
      run: echo "✅ Todos os testes passaram com sucesso!"
    
    - name: ⚠️ Testes com Falhas
      if: needs.testes-producao.result == 'failure' || needs.testes-novos.result == 'failure'
      run: |
        echo "⚠️ Alguns testes falharam. Verificar relatórios."
        exit 1