name: 🧪 QA - Testes Automatizados ERP

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Permitir execução manual

permissions:
  contents: read
  actions: write

jobs:
  testes-producao:
    name: ✅ Validar Casos de Produção
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
      fail-fast: false # Continuar mesmo se um falhar
    
    steps:
    - name: 📥 Checkout código
      uses: actions/checkout@v4
    
    - name: 🟢 Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: 📦 Instalar dependências
      run: npm ci
    
    - name: 🌐 Setup Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        google-chrome --version
    
    - name: 🧪 Executar Testes de Produção
      run: |
        export HEADLESS=true
        npm run test:producao || true
      continue-on-error: true
    
    - name: 📊 Upload Relatório de Produção
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: relatorio-producao-node-${{ matrix.node-version }}
        path: reports/relatorio-producao.json
        retention-days: 30
        if-no-files-found: warn
    
    - name: 📸 Upload Screenshots (se houver falhas)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: screenshots-producao-node-${{ matrix.node-version }}
        path: screenshots/
        retention-days: 7
        if-no-files-found: ignore

  testes-novos:
    name: 🆕 Executar Novos Casos de Teste
    runs-on: ubuntu-latest
    needs: testes-producao
    if: always() # Executar mesmo se testes-producao falhar
    
    steps:
    - name: 📥 Checkout código
      uses: actions/checkout@v4
    
    - name: 🟢 Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: 📦 Instalar dependências
      run: npm ci
    
    - name: 🌐 Setup Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: 🧪 Executar Novos Casos de Teste
      run: |
        export HEADLESS=true
        npm run test:novos || true
      continue-on-error: true
    
    - name: 📊 Upload Relatório Novos Casos
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: relatorio-novos-casos
        path: reports/relatorio-novos.json
        retention-days: 30
        if-no-files-found: warn

  analise-qualidade:
    name: 📈 Análise de Qualidade
    runs-on: ubuntu-latest
    needs: [testes-producao, testes-novos]
    if: always()
    
    steps:
    - name: 📥 Checkout código
      uses: actions/checkout@v4
    
    - name: 📊 Download Relatórios
      uses: actions/download-artifact@v4
      with:
        path: reports-consolidados/
      continue-on-error: true
    
    - name: 📈 Gerar Resumo
      run: |
        echo "## 📊 Resumo da Execução" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ✅ Testes de Produção" >> $GITHUB_STEP_SUMMARY
        echo "- Node 18.x: Executado" >> $GITHUB_STEP_SUMMARY
        echo "- Node 20.x: Executado" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🆕 Novos Casos de Teste" >> $GITHUB_STEP_SUMMARY
        echo "- Status: Executado" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "📄 Relatórios disponíveis nos artifacts da execução" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🔗 Links" >> $GITHUB_STEP_SUMMARY
        echo "- [Documentação Completa](https://github.com/${{ github.repository }}#readme)" >> $GITHUB_STEP_SUMMARY
        echo "- [Conhecimento em Módulos ERP](https://github.com/${{ github.repository }}/blob/main/docs/CONHECIMENTO-ERP.md)" >> $GITHUB_STEP_SUMMARY

  notificacao:
    name: 📧 Status Final
    runs-on: ubuntu-latest
    needs: [testes-producao, testes-novos]
    if: always()
    
    steps:
    - name: ✅ Resultado da Execução
      run: |
        echo "📊 Status dos Jobs:"
        echo "- Testes Produção: ${{ needs.testes-producao.result }}"
        echo "- Testes Novos: ${{ needs.testes-novos.result }}"
        
        if [ "${{ needs.testes-producao.result }}" == "success" ] && [ "${{ needs.testes-novos.result }}" == "success" ]; then
          echo "✅ Todos os testes executaram com sucesso!"
          exit 0
        else
          echo "⚠️ Alguns testes apresentaram problemas. Verificar logs acima."
          exit 0
        fi